Handle all magic link front end changes
lacortes/karly-capstone pull request #25
Opened 2022-03-18 06:11 UTC by jdhan96

Please check this

2022-03-18 07:28 UTC, lacortes requested changes

2022-03-18 07:28 UTC, lacortes commented on src/index.js
> +const comingSoon = false;
Let's leave it true for now

2022-03-18 21:10 UTC, jdhan96 commented on src/index.js
> +const comingSoon = false;
Done

2022-03-21 07:05 UTC, lacortes approved these changes

2022-03-21 07:05 UTC, lacortes commented on src/index.js
> +const comingSoon = false;
oh shoot! Sorry, this should be `true`

2022-03-21 07:05 UTC, merged